/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shoppe.view;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author ASUS TUF
 */
public class giohangview extends javax.swing.JFrame {

    /**
     * Creates new form giohangview
     */
    public giohangview() {
        initComponents();
      this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        trangchu = new javax.swing.JLabel();
        listgiohang = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        formhang4 = new javax.swing.JPanel();
        anhgiohang4 = new javax.swing.JLabel();
        txttengiohang4 = new javax.swing.JLabel();
        txtgia4 = new javax.swing.JLabel();
        btntru4 = new javax.swing.JLabel();
        btncong4 = new javax.swing.JLabel();
        txtsoluong4 = new javax.swing.JLabel();
        txttratien4 = new javax.swing.JLabel();
        cb4 = new javax.swing.JCheckBox();
        formhang1 = new javax.swing.JPanel();
        anhgiohang1 = new javax.swing.JLabel();
        txttengiohang1 = new javax.swing.JLabel();
        txtgia1 = new javax.swing.JLabel();
        btntru1 = new javax.swing.JLabel();
        btncong1 = new javax.swing.JLabel();
        txtsoluong1 = new javax.swing.JLabel();
        txttratien1 = new javax.swing.JLabel();
        cb1 = new javax.swing.JCheckBox();
        formhang2 = new javax.swing.JPanel();
        anhgiohang2 = new javax.swing.JLabel();
        txttengiohang2 = new javax.swing.JLabel();
        txtgia2 = new javax.swing.JLabel();
        btntru2 = new javax.swing.JLabel();
        btncong2 = new javax.swing.JLabel();
        txtsoluong2 = new javax.swing.JLabel();
        txttratien2 = new javax.swing.JLabel();
        cb2 = new javax.swing.JCheckBox();
        thongbao = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnmuangay = new javax.swing.JButton();
        formthanhtoan = new javax.swing.JPanel();
        txttongtienhang = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnmuahang = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtsohang = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        trangchu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trangchugiohang.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(trangchu)
                .addContainerGap(1239, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(trangchu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        formhang4.setBackground(new java.awt.Color(255, 255, 255));

        anhgiohang4.setBackground(new java.awt.Color(255, 51, 51));

        txttengiohang4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txttengiohang4.setText("1111");

        txtgia4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtgia4.setForeground(new java.awt.Color(255, 102, 102));
        txtgia4.setText("1.11");

        btntru4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btntru4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btntru4.setText("-");
        btntru4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btncong4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btncong4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btncong4.setText("+");
        btncong4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtsoluong4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtsoluong4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtsoluong4.setText("1");
        txtsoluong4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txttratien4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txttratien4.setForeground(new java.awt.Color(255, 51, 51));
        txttratien4.setText("jLabel4");

        javax.swing.GroupLayout formhang4Layout = new javax.swing.GroupLayout(formhang4);
        formhang4.setLayout(formhang4Layout);
        formhang4Layout.setHorizontalGroup(
            formhang4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formhang4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cb4)
                .addGap(12, 12, 12)
                .addComponent(anhgiohang4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(formhang4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formhang4Layout.createSequentialGroup()
                        .addGroup(formhang4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(formhang4Layout.createSequentialGroup()
                                .addGap(595, 595, 595)
                                .addComponent(txtgia4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(247, 247, 247))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formhang4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btntru4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtsoluong4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(formhang4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(formhang4Layout.createSequentialGroup()
                                .addComponent(btncong4, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                                .addGap(284, 284, 284))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formhang4Layout.createSequentialGroup()
                                .addComponent(txttratien4, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27))))
                    .addGroup(formhang4Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(txttengiohang4, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        formhang4Layout.setVerticalGroup(
            formhang4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formhang4Layout.createSequentialGroup()
                .addGroup(formhang4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formhang4Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(txttratien4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addGroup(formhang4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtsoluong4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(formhang4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btntru4, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                                .addComponent(btncong4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(formhang4Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(txtgia4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(formhang4Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(formhang4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txttengiohang4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(anhgiohang4, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(formhang4Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(cb4)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        formhang1.setBackground(new java.awt.Color(255, 255, 255));

        anhgiohang1.setBackground(new java.awt.Color(255, 51, 51));

        txttengiohang1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        txtgia1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtgia1.setForeground(new java.awt.Color(255, 51, 51));

        btntru1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btntru1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btntru1.setText("-");
        btntru1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btncong1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btncong1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btncong1.setText("+");
        btncong1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtsoluong1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtsoluong1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtsoluong1.setText("1");
        txtsoluong1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txttratien1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txttratien1.setForeground(new java.awt.Color(255, 51, 51));
        txttratien1.setText("jLabel4");

        javax.swing.GroupLayout formhang1Layout = new javax.swing.GroupLayout(formhang1);
        formhang1.setLayout(formhang1Layout);
        formhang1Layout.setHorizontalGroup(
            formhang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formhang1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cb1)
                .addGap(12, 12, 12)
                .addComponent(anhgiohang1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(formhang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formhang1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(txttengiohang1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(206, 206, 206)
                        .addComponent(txtgia1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(247, 247, 247))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formhang1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btntru1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtsoluong1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(formhang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formhang1Layout.createSequentialGroup()
                        .addComponent(btncong1, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                        .addGap(284, 284, 284))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formhang1Layout.createSequentialGroup()
                        .addComponent(txttratien1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
        );
        formhang1Layout.setVerticalGroup(
            formhang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formhang1Layout.createSequentialGroup()
                .addGroup(formhang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formhang1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(txttengiohang1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(formhang1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(anhgiohang1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(formhang1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(txttratien1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addGroup(formhang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtsoluong1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(formhang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btntru1, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                                .addComponent(btncong1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(formhang1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(txtgia1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(formhang1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(cb1)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        formhang2.setBackground(new java.awt.Color(255, 255, 255));

        anhgiohang2.setBackground(new java.awt.Color(255, 51, 51));

        txttengiohang2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txttengiohang2.setText("ten");

        txtgia2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtgia2.setForeground(new java.awt.Color(255, 51, 51));
        txtgia2.setText("gia");

        btntru2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btntru2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btntru2.setText("-");
        btntru2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btncong2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btncong2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btncong2.setText("+");
        btncong2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtsoluong2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtsoluong2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtsoluong2.setText("1");
        txtsoluong2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txttratien2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txttratien2.setForeground(new java.awt.Color(255, 51, 51));
        txttratien2.setText("jLabel4");

        javax.swing.GroupLayout formhang2Layout = new javax.swing.GroupLayout(formhang2);
        formhang2.setLayout(formhang2Layout);
        formhang2Layout.setHorizontalGroup(
            formhang2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formhang2Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(cb2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(anhgiohang2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(formhang2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formhang2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(txttengiohang2, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(206, 206, 206)
                        .addComponent(txtgia2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(247, 247, 247))
                    .addGroup(formhang2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btntru2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtsoluong2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(formhang2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formhang2Layout.createSequentialGroup()
                        .addComponent(btncong2, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                        .addGap(284, 284, 284))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formhang2Layout.createSequentialGroup()
                        .addComponent(txttratien2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
        );
        formhang2Layout.setVerticalGroup(
            formhang2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formhang2Layout.createSequentialGroup()
                .addGroup(formhang2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formhang2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(txttengiohang2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(formhang2Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(txttratien2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addGroup(formhang2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtsoluong2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(formhang2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btntru2, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                                .addComponent(btncong2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(formhang2Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(txtgia2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(formhang2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(anhgiohang2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(formhang2Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(cb2)))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(formhang4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(formhang1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(formhang2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 130, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(formhang4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formhang1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formhang2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(518, Short.MAX_VALUE))
        );

        listgiohang.setViewportView(jPanel2);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/giohangtrong.png"))); // NOI18N

        btnmuangay.setBackground(new java.awt.Color(255, 102, 102));
        btnmuangay.setText("Mua Ngay");

        javax.swing.GroupLayout thongbaoLayout = new javax.swing.GroupLayout(thongbao);
        thongbao.setLayout(thongbaoLayout);
        thongbaoLayout.setHorizontalGroup(
            thongbaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thongbaoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(thongbaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, thongbaoLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(659, 659, 659))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, thongbaoLayout.createSequentialGroup()
                        .addComponent(btnmuangay)
                        .addGap(736, 736, 736))))
        );
        thongbaoLayout.setVerticalGroup(
            thongbaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thongbaoLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(btnmuangay)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        formthanhtoan.setBackground(new java.awt.Color(255, 255, 255));

        txttongtienhang.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txttongtienhang.setForeground(new java.awt.Color(255, 0, 0));
        txttongtienhang.setText("0");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("đ");

        btnmuahang.setBackground(new java.awt.Color(255, 51, 51));
        btnmuahang.setText("jButton1");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Tổng Tiền Hàng:");

        txtsohang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtsohang.setText("(0 số hàng)");

        javax.swing.GroupLayout formthanhtoanLayout = new javax.swing.GroupLayout(formthanhtoan);
        formthanhtoan.setLayout(formthanhtoanLayout);
        formthanhtoanLayout.setHorizontalGroup(
            formthanhtoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formthanhtoanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtsohang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txttongtienhang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnmuahang)
                .addGap(160, 160, 160))
        );
        formthanhtoanLayout.setVerticalGroup(
            formthanhtoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formthanhtoanLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(formthanhtoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formthanhtoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtsohang)
                        .addComponent(jLabel3))
                    .addGroup(formthanhtoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txttongtienhang)
                        .addComponent(btnmuahang)))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(thongbao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(listgiohang, javax.swing.GroupLayout.DEFAULT_SIZE, 1447, Short.MAX_VALUE)
                    .addComponent(formthanhtoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(thongbao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listgiohang, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(formthanhtoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(giohangview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(giohangview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(giohangview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(giohangview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new giohangview().setVisible(true);
            }
        });
    }

    public JButton getBtnmuahang() {
        return btnmuahang;
    }

    public JPanel getFormthanhtoan() {
        return formthanhtoan;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public JLabel getTxttongtienhang() {
        return txttongtienhang;
    }

    public JCheckBox getCb1() {
        return cb1;
    }

    public JButton getBtnmuangay() {
        return btnmuangay;
    }

    public JCheckBox getCb2() {
        return cb2;
    }

    public JLabel getTrangchu() {
        return trangchu;
    }

    public JLabel getAnhgiohang1() {
        return anhgiohang1;
    }

    public JLabel getAnhgiohang2() {
        return anhgiohang2;
    }

    public JLabel getAnhgiohang4() {
        return anhgiohang4;
    }

    public JLabel getBtncong1() {
        return btncong1;
    }

    public JLabel getBtncong2() {
        return btncong2;
    }

    public JLabel getBtncong4() {
        return btncong4;
    }

    public JLabel getBtntru1() {
        return btntru1;
    }

    public JLabel getBtntru2() {
        return btntru2;
    }

    public JLabel getBtntru4() {
        return btntru4;
    }

    public JCheckBox getCb4() {
        return cb4;
    }

    public JPanel getFormhang1() {
        return formhang1;
    }

    public JPanel getFormhang2() {
        return formhang2;
    }

    public JPanel getFormhang4() {
        return formhang4;
    }

    public JLabel getjLabel1() {
        return trangchu;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public JScrollPane getListgiohang() {
        return listgiohang;
    }

    public JLabel getTxtgia1() {
        return txtgia1;
    }

    public JLabel getTxtgia2() {
        return txtgia2;
    }

    public JLabel getTxtgia4() {
        return txtgia4;
    }

    public JLabel getTxtsoluong1() {
        return txtsoluong1;
    }

    public JLabel getTxtsoluong2() {
        return txtsoluong2;
    }

    public JLabel getTxtsoluong4() {
        return txtsoluong4;
    }

    public JLabel getTxttengiohang1() {
        return txttengiohang1;
    }

    public JLabel getTxttengiohang2() {
        return txttengiohang2;
    }

    public JLabel getTxttengiohang4() {
        return txttengiohang4;
    }

    public JLabel getTxttratien1() {
        return txttratien1;
    }

    public JLabel getTxttratien2() {
        return txttratien2;
    }

    public JLabel getTxttratien4() {
        return txttratien4;
    }

    public JPanel getThongbao() {
        return thongbao;
    }

    
   

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anhgiohang1;
    private javax.swing.JLabel anhgiohang2;
    private javax.swing.JLabel anhgiohang4;
    private javax.swing.JLabel btncong1;
    private javax.swing.JLabel btncong2;
    private javax.swing.JLabel btncong4;
    private javax.swing.JButton btnmuahang;
    private javax.swing.JButton btnmuangay;
    private javax.swing.JLabel btntru1;
    private javax.swing.JLabel btntru2;
    private javax.swing.JLabel btntru4;
    private javax.swing.JCheckBox cb1;
    private javax.swing.JCheckBox cb2;
    private javax.swing.JCheckBox cb4;
    private javax.swing.JPanel formhang1;
    private javax.swing.JPanel formhang2;
    private javax.swing.JPanel formhang4;
    private javax.swing.JPanel formthanhtoan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane listgiohang;
    private javax.swing.JPanel thongbao;
    private javax.swing.JLabel trangchu;
    private javax.swing.JLabel txtgia1;
    private javax.swing.JLabel txtgia2;
    private javax.swing.JLabel txtgia4;
    private javax.swing.JLabel txtsohang;
    private javax.swing.JLabel txtsoluong1;
    private javax.swing.JLabel txtsoluong2;
    private javax.swing.JLabel txtsoluong4;
    private javax.swing.JLabel txttengiohang1;
    private javax.swing.JLabel txttengiohang2;
    private javax.swing.JLabel txttengiohang4;
    private javax.swing.JLabel txttongtienhang;
    private javax.swing.JLabel txttratien1;
    private javax.swing.JLabel txttratien2;
    private javax.swing.JLabel txttratien4;
    // End of variables declaration//GEN-END:variables


}
