/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shoppe.view;

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextField;


/**
 *
 * @author ASUS TUF
 */
public class indexview extends javax.swing.JFrame {

    /**
     * Creates new form index
     */
    private String ten;

    public void setTen(String ten) {
        this.ten = ten;
        txtten.setVisible(true);
        txtten.setText(ten);
        dangki.setVisible(false);
        btndangxuat.setVisible(true);
        dangnhap.setVisible(false);
    
    }

    public indexview() {
        initComponents();
         this.setLocationRelativeTo(this);
        txtten.setVisible(false);
btndangxuat.setVisible(false);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dangki = new javax.swing.JLabel();
        dangnhap = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txttimkiem = new javax.swing.JTextField();
        btntimkiem = new javax.swing.JLabel();
        txttenshop = new javax.swing.JLabel();
        btngiohang = new javax.swing.JLabel();
        txtten = new javax.swing.JLabel();
        btndangxuat = new javax.swing.JLabel();
        btnthemsanpham = new javax.swing.JLabel();
        btntrangchu = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jpsp1 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        lbimgsanpham1 = new javax.swing.JLabel();
        lbtensanpham1 = new javax.swing.JLabel();
        lbgiasanpham1 = new javax.swing.JLabel();
        jpsp2 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        lbimgsanpham2 = new javax.swing.JLabel();
        lbgiasanpham2 = new javax.swing.JLabel();
        lbtensanpham2 = new javax.swing.JLabel();
        jpsp3 = new javax.swing.JPanel();
        lbgiasanpham3 = new javax.swing.JLabel();
        lbtensanpham3 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        lbimgsanpham3 = new javax.swing.JLabel();
        jpsp4 = new javax.swing.JPanel();
        lbtensanpham4 = new javax.swing.JLabel();
        lbgiasanpham4 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        lbimgsanpham4 = new javax.swing.JLabel();
        jpsp5 = new javax.swing.JPanel();
        lbgiasanpham5 = new javax.swing.JLabel();
        lbtensanpham5 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        lbimgsanpham5 = new javax.swing.JLabel();
        jpsp6 = new javax.swing.JPanel();
        lbgiasanpham6 = new javax.swing.JLabel();
        lbtensanpham6 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        lbimgsanpham6 = new javax.swing.JLabel();
        jpsp7 = new javax.swing.JPanel();
        lbgiasanpham7 = new javax.swing.JLabel();
        lbtensanpham7 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        lbimgsanpham7 = new javax.swing.JLabel();
        jpsp8 = new javax.swing.JPanel();
        lbgiasanpham8 = new javax.swing.JLabel();
        lbtensanpham8 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        lbimgsanpham8 = new javax.swing.JLabel();
        jpsp9 = new javax.swing.JPanel();
        lbgiasanpham9 = new javax.swing.JLabel();
        lbtensanpham9 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        lbimgsanpham9 = new javax.swing.JLabel();
        jpsp10 = new javax.swing.JPanel();
        lbgiasanpham10 = new javax.swing.JLabel();
        lbtensanpham10 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        lbimgsanpham10 = new javax.swing.JLabel();
        jpsp11 = new javax.swing.JPanel();
        lbgiasanpham11 = new javax.swing.JLabel();
        lbtensanpham11 = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        lbimgsanpham11 = new javax.swing.JLabel();
        jpsp12 = new javax.swing.JPanel();
        lbgiasanpham12 = new javax.swing.JLabel();
        lbtensanpham12 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        lbimgsanpham12 = new javax.swing.JLabel();
        btnxemthem = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));

        dangki.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dangki.setForeground(new java.awt.Color(255, 255, 255));
        dangki.setText("Đăng Kí");
        dangki.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dangkiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dangkiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dangkiMouseExited(evt);
            }
        });

        dangnhap.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dangnhap.setForeground(new java.awt.Color(255, 255, 255));
        dangnhap.setText("Đăng Nhập");
        dangnhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dangnhapMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dangnhapMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dangnhapMouseExited(evt);
            }
        });

        txttimkiem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 911, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txttimkiem, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        btntimkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/timkiem.png"))); // NOI18N

        txttenshop.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txttenshop.setForeground(new java.awt.Color(255, 255, 255));

        btngiohang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/giohang.png"))); // NOI18N

        txtten.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtten.setForeground(new java.awt.Color(255, 255, 255));
        txtten.setText("jLabel4");
        txtten.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txttenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txttenMouseExited(evt);
            }
        });

        btndangxuat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btndangxuat.setForeground(new java.awt.Color(255, 255, 255));
        btndangxuat.setText("Đăng Xuất");
        btndangxuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btndangxuatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btndangxuatMouseExited(evt);
            }
        });

        btnthemsanpham.setText("Thêm Sản Phẩm");

        btntrangchu.setBackground(new java.awt.Color(255, 51, 51));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FAKESHOPPE");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logoindex.png"))); // NOI18N

        javax.swing.GroupLayout btntrangchuLayout = new javax.swing.GroupLayout(btntrangchu);
        btntrangchu.setLayout(btntrangchuLayout);
        btntrangchuLayout.setHorizontalGroup(
            btntrangchuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btntrangchuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        btntrangchuLayout.setVerticalGroup(
            btntrangchuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btntrangchuLayout.createSequentialGroup()
                .addGroup(btntrangchuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(btntrangchuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(btntrangchuLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txttenshop, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(btnthemsanpham)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(dangki, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dangnhap)
                .addGap(20, 20, 20)
                .addComponent(txtten, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btntrangchu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 890, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btntimkiem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btndangxuat))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btngiohang)
                        .addGap(150, 150, 150))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txttenshop)
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btntimkiem)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(btngiohang)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtten)
                            .addComponent(dangnhap)
                            .addComponent(dangki)
                            .addComponent(btnthemsanpham))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btndangxuat)
                            .addComponent(btntrangchu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        jScrollPane1.setBackground(new java.awt.Color(255, 51, 51));
        jScrollPane1.setBorder(null);
        jScrollPane1.setForeground(new java.awt.Color(255, 51, 51));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel3.setBackground(new java.awt.Color(153, 255, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1513, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 374, Short.MAX_VALUE)
        );

        jpsp1.setBackground(new java.awt.Color(255, 255, 255));
        jpsp1.setPreferredSize(new java.awt.Dimension(205, 0));
        jpsp1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpsp1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpsp1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbimgsanpham1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbimgsanpham1, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
        );

        lbtensanpham1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbtensanpham1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        lbgiasanpham1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbgiasanpham1.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jpsp1Layout = new javax.swing.GroupLayout(jpsp1);
        jpsp1.setLayout(jpsp1Layout);
        jpsp1Layout.setHorizontalGroup(
            jpsp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpsp1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbgiasanpham1, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
            .addGroup(jpsp1Layout.createSequentialGroup()
                .addComponent(lbtensanpham1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpsp1Layout.setVerticalGroup(
            jpsp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpsp1Layout.createSequentialGroup()
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbtensanpham1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbgiasanpham1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jpsp2.setBackground(new java.awt.Color(255, 255, 255));
        jpsp2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpsp2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpsp2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbimgsanpham2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbimgsanpham2, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
        );

        lbgiasanpham2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbgiasanpham2.setForeground(new java.awt.Color(255, 51, 51));

        lbtensanpham2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbtensanpham2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jpsp2Layout = new javax.swing.GroupLayout(jpsp2);
        jpsp2.setLayout(jpsp2Layout);
        jpsp2Layout.setHorizontalGroup(
            jpsp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpsp2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbgiasanpham2, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
            .addGroup(jpsp2Layout.createSequentialGroup()
                .addComponent(lbtensanpham2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpsp2Layout.setVerticalGroup(
            jpsp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpsp2Layout.createSequentialGroup()
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbtensanpham2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbgiasanpham2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jpsp3.setBackground(new java.awt.Color(255, 255, 255));

        lbgiasanpham3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbgiasanpham3.setForeground(new java.awt.Color(255, 51, 51));

        lbtensanpham3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbtensanpham3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbimgsanpham3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbimgsanpham3, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpsp3Layout = new javax.swing.GroupLayout(jpsp3);
        jpsp3.setLayout(jpsp3Layout);
        jpsp3Layout.setHorizontalGroup(
            jpsp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpsp3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbgiasanpham3, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
            .addGroup(jpsp3Layout.createSequentialGroup()
                .addComponent(lbtensanpham3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpsp3Layout.setVerticalGroup(
            jpsp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpsp3Layout.createSequentialGroup()
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbtensanpham3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(lbgiasanpham3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpsp4.setBackground(new java.awt.Color(255, 255, 255));

        lbtensanpham4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbtensanpham4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        lbgiasanpham4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbgiasanpham4.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbimgsanpham4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbimgsanpham4, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpsp4Layout = new javax.swing.GroupLayout(jpsp4);
        jpsp4.setLayout(jpsp4Layout);
        jpsp4Layout.setHorizontalGroup(
            jpsp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpsp4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbgiasanpham4, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
            .addGroup(jpsp4Layout.createSequentialGroup()
                .addComponent(lbtensanpham4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpsp4Layout.setVerticalGroup(
            jpsp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpsp4Layout.createSequentialGroup()
                .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbtensanpham4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lbgiasanpham4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jpsp5.setBackground(new java.awt.Color(255, 255, 255));

        lbgiasanpham5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbgiasanpham5.setForeground(new java.awt.Color(255, 51, 51));

        lbtensanpham5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbtensanpham5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbimgsanpham5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbimgsanpham5, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpsp5Layout = new javax.swing.GroupLayout(jpsp5);
        jpsp5.setLayout(jpsp5Layout);
        jpsp5Layout.setHorizontalGroup(
            jpsp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpsp5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbgiasanpham5, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
            .addGroup(jpsp5Layout.createSequentialGroup()
                .addComponent(lbtensanpham5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpsp5Layout.setVerticalGroup(
            jpsp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpsp5Layout.createSequentialGroup()
                .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbtensanpham5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbgiasanpham5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jpsp6.setBackground(new java.awt.Color(255, 255, 255));

        lbgiasanpham6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbgiasanpham6.setForeground(new java.awt.Color(255, 51, 51));

        lbtensanpham6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbtensanpham6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbimgsanpham6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbimgsanpham6, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpsp6Layout = new javax.swing.GroupLayout(jpsp6);
        jpsp6.setLayout(jpsp6Layout);
        jpsp6Layout.setHorizontalGroup(
            jpsp6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpsp6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbgiasanpham6, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
            .addGroup(jpsp6Layout.createSequentialGroup()
                .addComponent(lbtensanpham6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpsp6Layout.setVerticalGroup(
            jpsp6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpsp6Layout.createSequentialGroup()
                .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbtensanpham6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbgiasanpham6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jpsp7.setBackground(new java.awt.Color(255, 255, 255));
        jpsp7.setPreferredSize(new java.awt.Dimension(205, 318));

        lbgiasanpham7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbgiasanpham7.setForeground(new java.awt.Color(255, 51, 51));

        lbtensanpham7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbtensanpham7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbimgsanpham7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbimgsanpham7, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpsp7Layout = new javax.swing.GroupLayout(jpsp7);
        jpsp7.setLayout(jpsp7Layout);
        jpsp7Layout.setHorizontalGroup(
            jpsp7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpsp7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbgiasanpham7, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
            .addGroup(jpsp7Layout.createSequentialGroup()
                .addComponent(lbtensanpham7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpsp7Layout.setVerticalGroup(
            jpsp7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpsp7Layout.createSequentialGroup()
                .addComponent(jPanel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbtensanpham7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbgiasanpham7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jpsp8.setBackground(new java.awt.Color(255, 255, 255));
        jpsp8.setPreferredSize(new java.awt.Dimension(205, 318));

        lbgiasanpham8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbgiasanpham8.setForeground(new java.awt.Color(255, 51, 51));

        lbtensanpham8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbtensanpham8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbimgsanpham8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbimgsanpham8, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpsp8Layout = new javax.swing.GroupLayout(jpsp8);
        jpsp8.setLayout(jpsp8Layout);
        jpsp8Layout.setHorizontalGroup(
            jpsp8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpsp8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbgiasanpham8, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
            .addGroup(jpsp8Layout.createSequentialGroup()
                .addComponent(lbtensanpham8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpsp8Layout.setVerticalGroup(
            jpsp8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpsp8Layout.createSequentialGroup()
                .addComponent(jPanel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbtensanpham8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbgiasanpham8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jpsp9.setBackground(new java.awt.Color(255, 255, 255));
        jpsp9.setPreferredSize(new java.awt.Dimension(205, 318));

        lbgiasanpham9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbgiasanpham9.setForeground(new java.awt.Color(255, 51, 51));

        lbtensanpham9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbtensanpham9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbimgsanpham9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbimgsanpham9, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpsp9Layout = new javax.swing.GroupLayout(jpsp9);
        jpsp9.setLayout(jpsp9Layout);
        jpsp9Layout.setHorizontalGroup(
            jpsp9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpsp9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbgiasanpham9, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
            .addGroup(jpsp9Layout.createSequentialGroup()
                .addComponent(lbtensanpham9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpsp9Layout.setVerticalGroup(
            jpsp9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpsp9Layout.createSequentialGroup()
                .addComponent(jPanel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbtensanpham9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbgiasanpham9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jpsp10.setBackground(new java.awt.Color(255, 255, 255));
        jpsp10.setPreferredSize(new java.awt.Dimension(205, 318));

        lbgiasanpham10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbgiasanpham10.setForeground(new java.awt.Color(255, 51, 51));

        lbtensanpham10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbtensanpham10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbimgsanpham10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbimgsanpham10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpsp10Layout = new javax.swing.GroupLayout(jpsp10);
        jpsp10.setLayout(jpsp10Layout);
        jpsp10Layout.setHorizontalGroup(
            jpsp10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpsp10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbgiasanpham10, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
            .addGroup(jpsp10Layout.createSequentialGroup()
                .addComponent(lbtensanpham10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpsp10Layout.setVerticalGroup(
            jpsp10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpsp10Layout.createSequentialGroup()
                .addComponent(jPanel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbtensanpham10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbgiasanpham10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jpsp11.setBackground(new java.awt.Color(255, 255, 255));
        jpsp11.setPreferredSize(new java.awt.Dimension(205, 334));

        lbgiasanpham11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbgiasanpham11.setForeground(new java.awt.Color(255, 51, 51));

        lbtensanpham11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbtensanpham11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbimgsanpham11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbimgsanpham11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpsp11Layout = new javax.swing.GroupLayout(jpsp11);
        jpsp11.setLayout(jpsp11Layout);
        jpsp11Layout.setHorizontalGroup(
            jpsp11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpsp11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbgiasanpham11, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
            .addGroup(jpsp11Layout.createSequentialGroup()
                .addComponent(lbtensanpham11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpsp11Layout.setVerticalGroup(
            jpsp11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpsp11Layout.createSequentialGroup()
                .addComponent(jPanel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbtensanpham11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbgiasanpham11, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jpsp12.setBackground(new java.awt.Color(255, 255, 255));
        jpsp12.setPreferredSize(new java.awt.Dimension(205, 318));

        lbgiasanpham12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbgiasanpham12.setForeground(new java.awt.Color(255, 51, 51));

        lbtensanpham12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbtensanpham12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbimgsanpham12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbimgsanpham12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpsp12Layout = new javax.swing.GroupLayout(jpsp12);
        jpsp12.setLayout(jpsp12Layout);
        jpsp12Layout.setHorizontalGroup(
            jpsp12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpsp12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbgiasanpham12, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
            .addGroup(jpsp12Layout.createSequentialGroup()
                .addComponent(lbtensanpham12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpsp12Layout.setVerticalGroup(
            jpsp12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpsp12Layout.createSequentialGroup()
                .addComponent(jPanel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbtensanpham12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbgiasanpham12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnxemthem.setText("XÊM THÊM");

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("HAPPE NEW YEAR");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1131, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jpsp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jpsp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jpsp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jpsp4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jpsp5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jpsp6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(595, 595, 595)
                                        .addComponent(btnxemthem, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jpsp7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jpsp8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jpsp9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jpsp10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jpsp11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jpsp12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpsp2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpsp1, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                    .addComponent(jpsp3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpsp4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpsp5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpsp6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpsp12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpsp7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpsp8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpsp9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpsp10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpsp11, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnxemthem, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(301, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 878, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txttenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txttenMouseExited
txtten.setForeground(Color.WHITE);
    }//GEN-LAST:event_txttenMouseExited

    private void txttenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txttenMouseEntered
txtten.setForeground(Color.YELLOW);
    }//GEN-LAST:event_txttenMouseEntered

    private void dangnhapMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dangnhapMouseExited
        dangnhap.setForeground(Color.WHITE);
    }//GEN-LAST:event_dangnhapMouseExited

    private void dangnhapMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dangnhapMouseEntered
        dangnhap.setForeground(Color.YELLOW);
    }//GEN-LAST:event_dangnhapMouseEntered

    private void dangnhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dangnhapMouseClicked
        
    }//GEN-LAST:event_dangnhapMouseClicked

    private void dangkiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dangkiMouseExited
        dangki.setForeground(Color.WHITE);
    }//GEN-LAST:event_dangkiMouseExited

    private void dangkiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dangkiMouseEntered
        dangki.setForeground(Color.YELLOW);
    }//GEN-LAST:event_dangkiMouseEntered

    private void dangkiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dangkiMouseClicked
        
    }//GEN-LAST:event_dangkiMouseClicked

    private void btndangxuatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndangxuatMouseEntered
      btndangxuat.setForeground(Color.YELLOW);
    }//GEN-LAST:event_btndangxuatMouseEntered

    private void btndangxuatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndangxuatMouseExited
       btndangxuat.setForeground(Color.WHITE);
    }//GEN-LAST:event_btndangxuatMouseExited

    private void jpsp1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpsp1MouseEntered
    
    }//GEN-LAST:event_jpsp1MouseEntered

    private void jpsp1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpsp1MouseExited
   
    }//GEN-LAST:event_jpsp1MouseExited

    private void jpsp2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpsp2MouseEntered
    
    }//GEN-LAST:event_jpsp2MouseEntered

    private void jpsp2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpsp2MouseExited
   
    }//GEN-LAST:event_jpsp2MouseExited


    public String getTen() {
        return ten;
    }

    public JPanel getjPanel10() {
        return jpsp6;
    }

    public JLabel getBtntimkiem() {
        return btntimkiem;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public JPanel getjPanel11() {
        return jpsp7;
    }

    public JPanel getjPanel12() {
        return jpsp8;
    }

    public JPanel getjPanel13() {
        return jpsp9;
    }

    public JPanel getjPanel14() {
        return jpsp10;
    }

    public JPanel getjPanel15() {
        return jpsp11;
    }

    public JPanel getjPanel16() {
        return jpsp12;
    }

    public JPanel getjPanel17() {
        return jPanel17;
    }

    public JPanel getjPanel18() {
        return jPanel18;
    }

    public JPanel getjPanel19() {
        return jPanel19;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public JPanel getjPanel20() {
        return jPanel20;
    }

    public JPanel getjPanel21() {
        return jPanel21;
    }

    public JPanel getjPanel22() {
        return jPanel22;
    }

    public JPanel getjPanel23() {
        return jPanel23;
    }

    public JPanel getjPanel24() {
        return jPanel24;
    }

    public JPanel getjPanel25() {
        return jPanel25;
    }

    public JPanel getjPanel26() {
        return jPanel26;
    }

    public JPanel getjPanel27() {
        return jPanel27;
    }

    public JPanel getjPanel28() {
        return jPanel28;
    }

    public JPanel getjPanel3() {
        return jPanel3;
    }

    public JPanel getjPanel5() {
        return jpsp1;
    }

    public JPanel getjPanel6() {
        return jpsp2;
    }

    public JPanel getjPanel7() {
        return jpsp3;
    }

    public JPanel getjPanel8() {
        return jpsp4;
    }

    public JPanel getjPanel9() {
        return jpsp5;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public JLabel getLbgiasanpham1() {
        return lbgiasanpham1;
    }

    public JLabel getLbgiasanpham10() {
        return lbgiasanpham10;
    }

    public JLabel getLbgiasanpham11() {
        return lbgiasanpham11;
    }

    public JLabel getLbgiasanpham12() {
        return lbgiasanpham12;
    }

    public JLabel getLbgiasanpham2() {
        return lbgiasanpham2;
    }

    public JLabel getLbgiasanpham3() {
        return lbgiasanpham3;
    }

    public JLabel getLbgiasanpham4() {
        return lbgiasanpham4;
    }

    public JLabel getLbgiasanpham5() {
        return lbgiasanpham5;
    }

    public JLabel getLbgiasanpham6() {
        return lbgiasanpham6;
    }

    public JLabel getLbgiasanpham7() {
        return lbgiasanpham7;
    }

    public JLabel getLbgiasanpham8() {
        return lbgiasanpham8;
    }

    public JLabel getLbgiasanpham9() {
        return lbgiasanpham9;
    }

    public JLabel getLbimgsanpham1() {
        return lbimgsanpham1;
    }

    public JLabel getLbimgsanpham10() {
        return lbimgsanpham10;
    }

    public JLabel getLbimgsanpham11() {
        return lbimgsanpham11;
    }

    public JLabel getLbimgsanpham12() {
        return lbimgsanpham12;
    }

    public JLabel getLbimgsanpham2() {
        return lbimgsanpham2;
    }

    public JLabel getLbimgsanpham3() {
        return lbimgsanpham3;
    }

    public JLabel getLbimgsanpham4() {
        return lbimgsanpham4;
    }

    public JLabel getLbimgsanpham5() {
        return lbimgsanpham5;
    }

    public JLabel getLbimgsanpham6() {
        return lbimgsanpham6;
    }

    public JLabel getLbimgsanpham7() {
        return lbimgsanpham7;
    }

    public JLabel getLbimgsanpham8() {
        return lbimgsanpham8;
    }

    public JLabel getLbimgsanpham9() {
        return lbimgsanpham9;
    }

    public JLabel getLbtensanpham1() {
        return lbtensanpham1;
    }

    public JLabel getLbtensanpham10() {
        return lbtensanpham10;
    }

    public JLabel getLbtensanpham11() {
        return lbtensanpham11;
    }

    public JLabel getLbtensanpham12() {
        return lbtensanpham12;
    }

    public JLabel getLbtensanpham2() {
        return lbtensanpham2;
    }

    public JLabel getLbtensanpham3() {
        return lbtensanpham3;
    }

    public JLabel getLbtensanpham4() {
        return lbtensanpham4;
    }

    public JLabel getLbtensanpham5() {
        return lbtensanpham5;
    }

    public JLabel getLbtensanpham6() {
        return lbtensanpham6;
    }

    public JLabel getLbtensanpham7() {
        return lbtensanpham7;
    }

    public JLabel getLbtensanpham8() {
        return lbtensanpham8;
    }

    /**
     * @param args the command line arguments
     */
    public JLabel getLbtensanpham9() {
        return lbtensanpham9;
    }

    public JLabel getBtndangxuat() {
        return btndangxuat;
    }

    public void setBtndangxuat(JLabel btndangxuat) {
        this.btndangxuat = btndangxuat;
    }

    public JLabel getBtngiohang() {
        return btngiohang;
    }

    public void setBtngiohang(JLabel btngiohang) {
        this.btngiohang = btngiohang;
    }

    public JLabel getDangki() {
        return dangki;
    }

    public void setDangki(JLabel dangki) {
        this.dangki = dangki;
    }

    public JLabel getDangnhap() {
        return dangnhap;
    }

    public void setDangnhap(JLabel dangnhap) {
        this.dangnhap = dangnhap;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return btntimkiem;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.btntimkiem = jLabel3;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JPanel getJpsp1() {
        return jpsp1;
    }

    public JPanel getJpsp10() {
        return jpsp10;
    }

    public JPanel getJpsp11() {
        return jpsp11;
    }

    public JPanel getJpsp12() {
        return jpsp12;
    }

    public JPanel getJpsp2() {
        return jpsp2;
    }

    public JPanel getJpsp3() {
        return jpsp3;
    }

    public JPanel getJpsp4() {
        return jpsp4;
    }

    public JPanel getJpsp5() {
        return jpsp5;
    }

    public JPanel getJpsp6() {
        return jpsp6;
    }

    public JPanel getJpsp7() {
        return jpsp7;
    }

    public JPanel getJpsp8() {
        return jpsp8;
    }

    public JPanel getJpsp9() {
        return jpsp9;
    }

    

   

    public JPanel getjPanel4() {
        return jPanel4;
    }

    public void setjPanel4(JPanel jPanel4) {
        this.jPanel4 = jPanel4;
    }

    public JLabel getTxtten() {
        return txtten;
    }

    public JPanel getBtntrangchu() {
        return btntrangchu;
    }

    public void setTxtten(JLabel txtten) {
        this.txtten = txtten;
    }

    public JLabel getTxttenshop() {
        return txttenshop;
    }

    public void setTxttenshop(JLabel txttenshop) {
        this.txttenshop = txttenshop;
    }

    public JTextField getTxttimkiem() {
        return txttimkiem;
    }

    public void setTxttimkiem(JTextField txttimkiem) {
        this.txttimkiem = txttimkiem;
    }

    public JLabel getBtnthemsanpham() {
        return btnthemsanpham;
    }

    public JButton getBtnxemthem() {
        return btnxemthem;
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btndangxuat;
    private javax.swing.JLabel btngiohang;
    private javax.swing.JLabel btnthemsanpham;
    private javax.swing.JLabel btntimkiem;
    private javax.swing.JPanel btntrangchu;
    private javax.swing.JButton btnxemthem;
    private javax.swing.JLabel dangki;
    private javax.swing.JLabel dangnhap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpsp1;
    private javax.swing.JPanel jpsp10;
    private javax.swing.JPanel jpsp11;
    private javax.swing.JPanel jpsp12;
    private javax.swing.JPanel jpsp2;
    private javax.swing.JPanel jpsp3;
    private javax.swing.JPanel jpsp4;
    private javax.swing.JPanel jpsp5;
    private javax.swing.JPanel jpsp6;
    private javax.swing.JPanel jpsp7;
    private javax.swing.JPanel jpsp8;
    private javax.swing.JPanel jpsp9;
    private javax.swing.JLabel lbgiasanpham1;
    private javax.swing.JLabel lbgiasanpham10;
    private javax.swing.JLabel lbgiasanpham11;
    private javax.swing.JLabel lbgiasanpham12;
    private javax.swing.JLabel lbgiasanpham2;
    private javax.swing.JLabel lbgiasanpham3;
    private javax.swing.JLabel lbgiasanpham4;
    private javax.swing.JLabel lbgiasanpham5;
    private javax.swing.JLabel lbgiasanpham6;
    private javax.swing.JLabel lbgiasanpham7;
    private javax.swing.JLabel lbgiasanpham8;
    private javax.swing.JLabel lbgiasanpham9;
    private javax.swing.JLabel lbimgsanpham1;
    private javax.swing.JLabel lbimgsanpham10;
    private javax.swing.JLabel lbimgsanpham11;
    private javax.swing.JLabel lbimgsanpham12;
    private javax.swing.JLabel lbimgsanpham2;
    private javax.swing.JLabel lbimgsanpham3;
    private javax.swing.JLabel lbimgsanpham4;
    private javax.swing.JLabel lbimgsanpham5;
    private javax.swing.JLabel lbimgsanpham6;
    private javax.swing.JLabel lbimgsanpham7;
    private javax.swing.JLabel lbimgsanpham8;
    private javax.swing.JLabel lbimgsanpham9;
    private javax.swing.JLabel lbtensanpham1;
    private javax.swing.JLabel lbtensanpham10;
    private javax.swing.JLabel lbtensanpham11;
    private javax.swing.JLabel lbtensanpham12;
    private javax.swing.JLabel lbtensanpham2;
    private javax.swing.JLabel lbtensanpham3;
    private javax.swing.JLabel lbtensanpham4;
    private javax.swing.JLabel lbtensanpham5;
    private javax.swing.JLabel lbtensanpham6;
    private javax.swing.JLabel lbtensanpham7;
    private javax.swing.JLabel lbtensanpham8;
    private javax.swing.JLabel lbtensanpham9;
    private javax.swing.JLabel txtten;
    private javax.swing.JLabel txttenshop;
    private javax.swing.JTextField txttimkiem;
    // End of variables declaration//GEN-END:variables
}
